---
- hosts: routers
  gather_facts: true
  connection: local

  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
      host: "{{ ansible_host }}"
      username: istore
  register: config

    - name: save output to /mnt/c/Users/diogo/Documents/backups
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "/mnt/c/Users/diogo/Documents/backups/show_run_{{ inventory_hostname }}.txt"
