---
- hosts: all
  user: root

  tasks:

    - name: update and upgrade Debian
      apt: upgrade=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

    - name: upgrade all packages Centos
      yum: name=* state=latest
      when: ansible_os_family == 'RedHat'
