---
- hosts: all
  vars:
    host_user: usuario
  tasks:
    - name: Copiando bashrc
      ansible.builtin.copy:
        src:  bashrcdeb
        dest: /home/{{host_user}}/.bashrc
        mode: '0644'
        owner: '{{ host_user }}'
        group: '{{ host_user }}'

...
