---
- hosts: all
  vars:
    db_user: 'zabbix'
    db_name: 'zabbix'
    db_password: 'wirveD5R8aNKAUiq4n9'
  tasks:
    - name: Instalando repositorio zabbix 6.4
      ansible.builtin.apt:
        deb: 'https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb'
        update_cache: yes

    - name: Instalando Zabbix e Postgresql
      ansible.builtin.package:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.2-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - postgresql
          - postgresql-contrib
          - acl
          - python3-pip
          - python3-psycopg2

    - name: Cria database zabbix
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: '{{ db_name }}'

    - name: Cria usuario zabbix e libera acesso a base zabbix
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        db: '{{ db_name }}'
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: ALL
    #- name: Removendo permissoes desnecessarios ao usuario
    #  become: true
    #  become_user: postgres
    #  postgresql_user: name={{ db_user }}
    #    role_attr_flags=NOSUPERUSER,NOCREATEDB
    #    state=present
    
    - name: Extraindo a base de dados
      become: true
      become_user: postgres
      ansible.builtin.shell: gunzip -c /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz > /tmp/server.sql
    
    - name: Importando base de dados
      become: true
      become_user: '{{ db_user }}'
      shell: psql {{ db_name }} < /tmp/server.sql
    
#    - name: Configurado DBPassword com senha criada
#      ansible.builtin.command: sed -i '/DBPassword=/a DBPassword={{ db_password }}' /etc/zabbix/zabbix_server.conf
#    
#    - name: Alterado Nginx Listen
#      ansible.builtin.command: sed -i '/listen          8080;/a listen          80;' /etc/zabbix/nginx.conf      
#    
#    - name: Alterado Nginx server_name
#      ansible.builtin.command: sed -i '/server_name example.com;/a server_name "{{ ansible_default_ipv4.address }}";' /etc/zabbix/nginx.conf
#      
#    - name: Reinicializando os serviços
#      ansible.builtin.command: sudo systemctl restart zabbix-server zabbix-agent nginx php8.2-fpm
#    
#    - name: Habilitando os serviços
#      ansible.builtin.command: sudo systemctl enbale zabbix-server zabbix-agent nginx php8.2-fpm
...