---
- hosts: all
  tasks:
        - name: Desabilitando repositorio enterprise
          ansible.builtin.command: sed -i 's/^deb/#&/' /etc/apt/sources.list.d/pve-enterprise.list
        
        - name: Desabilitando repositorio ceph enterprise
          ansible.builtin.command: sed -i 's/^deb/#&/' /etc/apt/sources.list.d/ceph.list

        - name: Habilitando repositorio no-subscription
          ansible.builtin.apt_repository:
            repo: 'deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }}  pve-no-subscription'
            state: present
            filename: pve-no-subscription

        - name: Habilitando repositorio ceph no-subscription
          ansible.builtin.apt_repository:
            repo: 'deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }}  no-subscription'
            state: present
            filename: ceph-no-subscription            
...
